typography_spectrum: 0.30894318013451993
color:
  brandColors:
    - '#f4f4f2'
    - '#214576'
    - '#0b0a0f'
    - '#de6567'
    - '#fd9996'
  brandStrength: 0
  lightness: 0.6631188793107867
  saturation: 0.18017235514707863
  rhythmicContrast: 0.25812265230342746
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25027
analytics:
  google: null
  facebook: null
  twitter: null
name: mainframefx
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: mffx
    id: e5fe3afc-fb0b-4ac3-95b9-ba539031eca9
    type: content
favicon: null
title: mffx
description: Better the Ever
purpose: []
