typography_spectrum: 0.30894318013451993
color:
  brandColors:
    - '#f4f4f2'
    - '#214576'
    - '#0b0a0f'
    - '#de6567'
    - '#fd9996'
  brandStrength: 0
  lightness: 0.6631188793107867
  saturation: 0.18017235514707863
  rhythmicContrast: 0.25812265230342746
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25027
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b4f9ef8a-2e56-4cbd-b9a8-10a90afa754d.jpg
name: mainframefx
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: mainframefx
    id: e5fe3afc-fb0b-4ac3-95b9-ba539031eca9
    type: content
  - name: 3D
    id: 30f9fdac-00e8-4d23-92e7-3c95420bc3f5
    type: content
  - name: 2D
    id: 3b7bfd60-b99f-485c-ae17-efb35928c2fe
    type: content
  - name: Info
    id: 894d0e6c-73eb-460f-9667-8e675c882a2a
    type: content
  - name: Contact
    id: f6ea1bb2-8022-4af0-80ab-35a86052672e
    type: content
favicon: null
title: We are better
description: ''
purpose: []
