typography_spectrum: 0.30894318013451993
color:
  brandColors:
    - '#f4f4f2'
    - '#214576'
    - '#0b0a0f'
    - '#de6567'
    - '#fd9996'
  brandStrength: 0
  lightness: 0.6631188793107867
  saturation: 0.18017235514707863
  rhythmicContrast: 0.25812265230342746
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25027
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: mainframefx
  email: info@mainframefx.com
  url: 'www,mainframefx.com'
logo: null
name: mainframefx
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: post & filmproduction
description: ''
purpose: []
