name: mainframefx
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30894318013451993
title: mffx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f2'
    - '#214576'
    - '#0b0a0f'
    - '#de6567'
    - '#fd9996'
  brandStrength: 0
  lightness: 0.6631188793107867
  saturation: 0.18017235514707863
  rhythmicContrast: 0.25812265230342746
purpose: []
